### PR TITLE
The iptv json structure has changed. This is one way to fix it

### PR DESCRIPTION
**Pull request by dcardin**
Implies a change of the documentation, or some handling of the rename within the module. 
If you want to keep the config names, tell me, I'll rework my quick fix

### CODE REVIEW

**Comment by deathbybandaid** [comment]
Looks like the config names would also need to change

**Comment by deathbybandaid** [comment]
As in these:

https://github.com/fHDHR/fHDHR_plugin_origin_IPTVorg/blob/main/iptvorg_conf.json

because it works hand-in-hand with

https://github.com/fHDHR/fHDHR_plugin_origin_IPTVorg/blob/main/origin/__init__.py#L43

**Comment by dcardin** [comment]
should I bump the version number?

**Comment by deathbybandaid** [comment]
I'll merge this, and we'll wait to bump version number until I can confirm it working on my end.

**Pull request merged**
